"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5o=mui7ey)k+gvs3wv(yoqgh&xid5!j8^@+pe-blp-uf9p7#@0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['aeroport-backend.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'air_services',
    'rest_framework',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# settings.py faylining eng oxiriga qo'shing:

JAZZMIN_SETTINGS = {
    # Tepadagi sarlavha
    "site_title": "Aeroport Admin",
    
    # Chap tepadagi katta yozuv
    "site_header": "Aeroport Boshqaruvi",
    
    # Kichik logo yozuvi
    "site_brand": "Aeroport Tizimi",
    
    # Kirish oynasidagi yozuv (Login screen)
    "welcome_sign": "Aeroport tizimiga xush kelibsiz!",
    
    # Pastdagi avtorlik huquqi
    "copyright": "Aeroport IT Department",
    
    # Ikonkalar (FontAwesome ishlatiladi)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        # Bizning modellar uchun maxsus ikonkalar:
        "air_services.Kategoriya": "fas fa-list-ul",
        "air_services.Mahsulot": "fas fa-hamburger",  # Burger ikonkasini qo'ydim :)
        "air_services.Parvoz": "fas fa-plane-departure", # Samolyot uchishi
        "air_services.XizmatKorsatishNuqtasi": "fas fa-store", # Do'kon
        "air_services.Yolovchi": "fas fa-suitcase-rolling", 
        "air_services.Aviakompaniya": "fas fa-plane-circle-check",
        "air_services.Chipta": "fas fa-ticket-alt",
        "air_services.Bagaj": "fas fa-luggage-cart",
        "air_services.Xodim": "fas fa-id-badge",# Turist chamadoni bilan
    },
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# settings.py ga qo'shing
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
# Media files sozlamalari (Rasm, video, audio fayllar uchun)
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')