# Generated by Django 6.0.2 on 2026-02-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parvoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qayerdan', models.CharField(max_length=100)),
                ('qayerga', models.CharField(max_length=100)),
                ('uchish_vaqti', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XizmatKorsatishNuqtasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('joylashuv', models.CharField(max_length=100)),
                ('ochilish_vaqti', models.TimeField()),
                ('yopilish_vaqti', models.TimeField()),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_services.kategoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasmi', models.ImageField(blank=True, null=True, upload_to='mahsulotlar/')),
                ('nuqta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='air_services.xizmatkorsatishnuqtasi')),
            ],
        ),
        migrations.CreateModel(
            name='Yolovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('pasport_raqam', models.CharField(max_length=20)),
                ('parvoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='air_services.parvoz')),
            ],
        ),
    ]
