# Generated by Django 6.0.2 on 2026-02-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviakompaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('kodi', models.CharField(max_length=10, unique=True)),
                ('logotipi', models.ImageField(blank=True, null=True, upload_to='aviakompaniyalar/')),
                ('veb_sayt', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aviakompaniya',
                'verbose_name_plural': 'Aviakompaniyalar',
            },
        ),
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='parvoz',
            options={'ordering': ['uchish_vaqti'], 'verbose_name': 'Parvoz', 'verbose_name_plural': 'Parvozlar'},
        ),
        migrations.AlterModelOptions(
            name='xizmatkorsatishnuqtasi',
            options={'verbose_name': 'Xizmat nuqtasi', 'verbose_name_plural': "Xizmat ko'rsatish nuqtalari"},
        ),
        migrations.AlterModelOptions(
            name='yolovchi',
            options={'verbose_name': "Yo'lovchi", 'verbose_name_plural': "Yo'lovchilar"},
        ),
        migrations.RemoveField(
            model_name='yolovchi',
            name='parvoz',
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='mavjud',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='bosh_narx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='holat',
            field=models.CharField(choices=[('rejalashtirilgan', 'Rejalashtirilgan'), ('kechikkan', 'Kechikkan'), ('bekor_qilingan', 'Bekor qilingan'), ('uchdi', 'Uchdi'), ('qondi', "Qo'ndi")], default='rejalashtirilgan', max_length=20),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='parvoz_raqami',
            field=models.CharField(default='UNKNOWN', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parvoz',
            name='qonish_vaqti',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='terminal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='umumiy_orindiqlar',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='xizmatkorsatishnuqtasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='xizmatkorsatishnuqtasi',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='xizmatlar/'),
        ),
        migrations.AddField(
            model_name='xizmatkorsatishnuqtasi',
            name='tavsif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yolovchi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='yolovchi',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='yolovchi',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yolovchi',
            name='tug_ilgan_sana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yolovchi',
            name='pasport_raqam',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='parvoz',
            name='aviakompaniya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parvozlar', to='air_services.aviakompaniya'),
        ),
        migrations.CreateModel(
            name='Chipta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orindiq_raqami', models.CharField(max_length=10)),
                ('sinf', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holat', models.CharField(choices=[('band', 'Band'), ('bekor', 'Bekor qilingan'), ('ishlatilgan', 'Ishlatilgan')], default='band', max_length=15)),
                ('bron_vaqti', models.DateTimeField(auto_now_add=True)),
                ('parvoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiptalar', to='air_services.parvoz')),
                ('yolovchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiptalar', to='air_services.yolovchi')),
            ],
            options={
                'verbose_name': 'Chipta',
                'verbose_name_plural': 'Chiptalar',
                'unique_together': {('parvoz', 'orindiq_raqami')},
            },
        ),
        migrations.CreateModel(
            name='Bagaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazni_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('holat', models.CharField(choices=[('qabul', 'Qabul qilindi'), ('yuklandi', 'Yuklanda'), ('yetkazildi', 'Yetkazildi'), ('yoqoldi', "Yo'qoldi")], default='qabul', max_length=15)),
                ('teg_raqami', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('chipta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagajlar', to='air_services.chipta')),
            ],
            options={
                'verbose_name': 'Bagaj',
                'verbose_name_plural': 'Bagajlar',
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('lavozim', models.CharField(choices=[('operator', 'Operator'), ('xavfsizlik', 'Xavfsizlik xodimi'), ('tozalovchi', 'Tozalovchi'), ('boshqaruvchi', 'Boshqaruvchi'), ('pilot', 'Pilot'), ('styuardessa', 'Styuardessa')], max_length=20)),
                ('smena', models.CharField(choices=[('kunduz', 'Kunduzgi (08:00-20:00)'), ('tun', 'Tungi (20:00-08:00)')], max_length=10)),
                ('telefon', models.CharField(max_length=20)),
                ('yollanma_sanasi', models.DateField()),
                ('faol', models.BooleanField(default=True)),
                ('ishlash_nuqtasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xodimlar', to='air_services.xizmatkorsatishnuqtasi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
